"""Added colors column to Palette

Revision ID: 5b08f18c7704
Revises: 49d0587baaf2
Create Date: 2024-11-22 21:21:19.111384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b08f18c7704'
down_revision = '49d0587baaf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('palette', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colors', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('palette', schema=None) as batch_op:
        batch_op.drop_column('colors')

    # ### end Alembic commands ###
